### ISSUE TITLE
feat: if a required security length is not reached, provide the one which fullfills the requirement

### ISSUE THREAD

**Issue by denknorr** [tshakalekholoane/wardstone#26]
**Is your feature request related to a problem? Please describe.**
It may be the case i expect to have a certain security level measured in bits and wardstone gets to know this somehow. Now i want that my application uses a certain cryptographic primitive, or it uses one which i actually do not see in the haystack. Now this primitive is not good enough for my expected security level, then it would be nice if wardstone could point me to a similar primitive which enables this.

**Describe the solution you'd like**
if i tell wardstone i want to have 200 Bits of security but i have not seen that AES-192 is chosen as a primitive, then it would be nice, if configured in that way via a parameter (either environment variable or on the stack) that wardstone tells me something like, this is too short for your required length, but there's AES-256 which fullfills that and can be chosen from the NIST standard.

This will not work in all cases and may be to complex to map though.

**Describe alternatives you've considered**
One alternative is, that wardstone returns all primitives which are better, if a certain condition is set, but this seems overwhelming. 

**Additional context**
We have to see if this is too complex to implement, and if the standards give enough room to actually choose from or if the standards for AES for example actually allow in combination with their other operations (blockmodi e.g.) actually allow this at all.

**Comment by denknorr** [comment]
Let's do an example:

The user wants to have 120 Bits of Security, and he uses a cryptographic library which has primitives with 80, 110, 120, 192 and 256 Bits of Security and the standard XYZ he adheres to allows the following Bits of Security: 110, 120 and 256.

Now we have two cases:

1. The user actually uses a primitive which only has 80 Bits of Security, then it is outside the range of the standard and an error should be returned, which suggests using a crypto primitive which has 120 Bits of Security. The error or notification should also note that the current security level is not compatible with the standard.

2. The user uses a cryptographic primitive which has 110 Bits of Security but wants 120 Bits of security. This is within the range of the standard, but as the users wants to have a higher level of security, he should get a message/notification, which says, yes this is within the standard, but it does not meet your expectation of security, but another primitive would called AES128 (for example) would enable that.

3. If the user wants 120 Bits of Security, but uses a primitive which has 128 Bits of Security, than there has to be no error or notification.

This of course would mean that the required level of security bits has to be given to the library, IF the user cares about it. If the users does not care about the actual level of security, this parameter can be null or not used. As long as the documentation is clear about it i am fine with both implementations.

**Comment by tshakalekholoane** [comment]
@denknorr, I think the following snippet would cover all the cases you mentioned. Can you confirm?

https://github.com/tshakalekholoane/wardstone/blob/3e84449cb38e4de7d98b08d774a775647777a620/src/standards/nist.rs#L75-L94

The screenshots from the standard for reference (the cutoff for security less than 128 bits is 2030).

![cutoff](https://github.com/tshakalekholoane/wardstone/assets/23554017/a9bf5c2f-83f0-45e5-b686-d08509ebfe51)

Supported hash functions and their strengths (for collision resistance).

![hash functions](https://github.com/tshakalekholoane/wardstone/assets/23554017/dbcf8059-4b53-43fc-88b0-29c9d658c710)

**Comment by denknorr** [comment]
Yes, that looks well.
